#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

"$ROOT_DIR/scripts/roadmap/check_issue_statuses.sh"
"$ROOT_DIR/scripts/roadmap/check_issue_dependencies.sh"
"$ROOT_DIR/scripts/roadmap/check_milestone_dependencies.py"
"$ROOT_DIR/scripts/roadmap/check_issue_evidence.sh"
"$ROOT_DIR/scripts/roadmap/check_architecture_boundaries.sh"
"$ROOT_DIR/scripts/test/architecture_boundaries.sh"
"$ROOT_DIR/scripts/test/sierra_primary_cairo_coupling_guard.sh"
"$ROOT_DIR/scripts/test/sierra_primary_without_cairo.sh"
"$ROOT_DIR/scripts/roadmap/check_pin_consistency.sh"
"$ROOT_DIR/scripts/roadmap/check_inventory_reproducibility.sh"
"$ROOT_DIR/scripts/roadmap/check_inventory_freshness.sh"
"$ROOT_DIR/scripts/roadmap/check_corelib_parity_freshness.sh"
"$ROOT_DIR/scripts/roadmap/check_crate_dependency_matrix_freshness.sh"
"$ROOT_DIR/scripts/roadmap/check_coverage_matrix_freshness.sh"
"$ROOT_DIR/scripts/roadmap/check_sierra_coverage_report_freshness.sh"
"$ROOT_DIR/scripts/roadmap/check_subset_ledger_sync.py"
"$ROOT_DIR/scripts/roadmap/check_effect_isolation.sh"
"$ROOT_DIR/scripts/roadmap/check_proof_obligations.sh"
"$ROOT_DIR/scripts/test/type_universe_regression.sh"
"$ROOT_DIR/scripts/test/effect_resource_regression.sh"
"$ROOT_DIR/scripts/test/semantic_state_regression.sh"
"$ROOT_DIR/scripts/test/eval_scalar_domain_isolation.sh"
"$ROOT_DIR/scripts/test/eval_unsupported_domain_failfast.sh"
"$ROOT_DIR/scripts/test/eval_integer_width_semantics.sh"
"$ROOT_DIR/scripts/test/eval_qm31_semantics.sh"
"$ROOT_DIR/scripts/test/eval_typed_resource_mixed.sh"
"$ROOT_DIR/scripts/test/canonicalization_regression.sh"
"$ROOT_DIR/scripts/test/proof_obligations_negative.sh"
"$ROOT_DIR/scripts/test/milestone_dependencies_negative.sh"
"$ROOT_DIR/scripts/test/sierra_primary_closure_negative.sh"
"$ROOT_DIR/scripts/test/sierra_surface_codegen.sh"
"$ROOT_DIR/scripts/test/sierra_codegen_snapshot.sh"
"$ROOT_DIR/scripts/test/deterministic_codegen.sh"
"$ROOT_DIR/scripts/test/sierra_hash_policy.sh"
"$ROOT_DIR/scripts/roadmap/check_failfast_policy_lock.sh"
"$ROOT_DIR/scripts/test/sierra_e2e.sh"
"$ROOT_DIR/scripts/test/sierra_scalar_e2e.sh"
"$ROOT_DIR/scripts/test/sierra_u128_range_checked_e2e.sh"
"$ROOT_DIR/scripts/test/sierra_differential.sh"
"$ROOT_DIR/scripts/test/sierra_u128_wrapping_differential.sh"

echo "all Sierra pipeline checks passed"
