#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export PATH="$HOME/.elan/bin:$PATH"

"$ROOT_DIR/scripts/lint/pedantic.sh"
"$ROOT_DIR/scripts/roadmap/check_issue_statuses.sh"
"$ROOT_DIR/scripts/roadmap/check_issue_dependencies.sh"
"$ROOT_DIR/scripts/roadmap/check_milestone_dependencies.py"
"$ROOT_DIR/scripts/roadmap/check_issue_evidence.sh"
"$ROOT_DIR/scripts/roadmap/check_architecture_boundaries.sh"
"$ROOT_DIR/scripts/test/architecture_boundaries.sh"
"$ROOT_DIR/scripts/test/sierra_primary_cairo_coupling_guard.sh"
"$ROOT_DIR/scripts/test/sierra_primary_without_cairo.sh"
"$ROOT_DIR/scripts/roadmap/check_pin_consistency.sh"
"$ROOT_DIR/scripts/roadmap/check_inventory_reproducibility.sh"
"$ROOT_DIR/scripts/roadmap/check_inventory_freshness.sh"
"$ROOT_DIR/scripts/roadmap/check_coverage_matrix_freshness.sh"
"$ROOT_DIR/scripts/roadmap/check_subset_ledger_sync.py"
"$ROOT_DIR/scripts/roadmap/check_effect_isolation.sh"
"$ROOT_DIR/scripts/roadmap/check_proof_obligations.sh"
(
  cd "$ROOT_DIR"
  lake build
)
"$ROOT_DIR/scripts/test/type_universe_regression.sh"
"$ROOT_DIR/scripts/test/effect_resource_regression.sh"
"$ROOT_DIR/scripts/test/semantic_state_regression.sh"
"$ROOT_DIR/scripts/test/eval_scalar_domain_isolation.sh"
"$ROOT_DIR/scripts/test/eval_unsupported_domain_failfast.sh"
"$ROOT_DIR/scripts/test/eval_integer_width_semantics.sh"
"$ROOT_DIR/scripts/test/eval_qm31_semantics.sh"
"$ROOT_DIR/scripts/test/eval_typed_resource_mixed.sh"
"$ROOT_DIR/scripts/test/canonicalization_regression.sh"
"$ROOT_DIR/scripts/test/proof_obligations_negative.sh"
"$ROOT_DIR/scripts/test/milestone_dependencies_negative.sh"
"$ROOT_DIR/scripts/test/codegen_snapshot.sh"
"$ROOT_DIR/scripts/test/e2e.sh"
"$ROOT_DIR/scripts/test/sierra_surface_codegen.sh"
"$ROOT_DIR/scripts/test/sierra_codegen_snapshot.sh"
"$ROOT_DIR/scripts/test/deterministic_codegen.sh"
"$ROOT_DIR/scripts/test/sierra_hash_policy.sh"
"$ROOT_DIR/scripts/roadmap/check_failfast_policy_lock.sh"
"$ROOT_DIR/scripts/test/sierra_e2e.sh"
"$ROOT_DIR/scripts/test/sierra_scalar_e2e.sh"
"$ROOT_DIR/scripts/test/sierra_u128_range_checked_e2e.sh"
"$ROOT_DIR/scripts/test/sierra_differential.sh"
"$ROOT_DIR/scripts/test/sierra_u128_wrapping_differential.sh"
"$ROOT_DIR/scripts/bench/check_optimizer_non_regression.sh"
"$ROOT_DIR/scripts/bench/check_optimizer_non_regression.sh" MyLeanContractCSEBench CSEBenchContract
"$ROOT_DIR/scripts/bench/check_artifact_passes.sh"

echo "all MVP quality checks passed"
