namespace LeanCairo.Backend.Scarb

def artifactLocatorScript : String :=
  "#!/usr/bin/env python3\n"
    ++ "\"\"\"Resolve Starknet contract artifact paths from Scarb artifacts index.\"\"\"\n"
    ++ "\n"
    ++ "import argparse\n"
    ++ "import json\n"
    ++ "from pathlib import Path\n"
    ++ "\n"
    ++ "\n"
    ++ "def main() -> int:\n"
    ++ "    parser = argparse.ArgumentParser()\n"
    ++ "    parser.add_argument('--index', required=True, help='Path to *.starknet_artifacts.json')\n"
    ++ "    parser.add_argument('--contract', default=None, help='Contract name in artifacts index')\n"
    ++ "    args = parser.parse_args()\n"
    ++ "\n"
    ++ "    index_path = Path(args.index)\n"
    ++ "    data = json.loads(index_path.read_text())\n"
    ++ "    contracts = data.get('contracts', [])\n"
    ++ "    if not contracts:\n"
    ++ "        raise SystemExit('No contracts found in artifacts index')\n"
    ++ "\n"
    ++ "    selected = None\n"
    ++ "    if args.contract is None:\n"
    ++ "        selected = contracts[0]\n"
    ++ "    else:\n"
    ++ "        for contract in contracts:\n"
    ++ "            if contract.get('contract_name') == args.contract:\n"
    ++ "                selected = contract\n"
    ++ "                break\n"
    ++ "    if selected is None:\n"
    ++ "        raise SystemExit(f\"Contract not found: {args.contract}\")\n"
    ++ "\n"
    ++ "    artifacts = selected.get('artifacts', {})\n"
    ++ "    base = index_path.parent\n"
    ++ "    sierra = artifacts.get('sierra')\n"
    ++ "    casm = artifacts.get('casm')\n"
    ++ "\n"
    ++ "    if sierra:\n"
    ++ "        print(str((base / sierra).resolve()))\n"
    ++ "    if casm:\n"
    ++ "        print(str((base / casm).resolve()))\n"
    ++ "    return 0\n"
    ++ "\n"
    ++ "\n"
    ++ "if __name__ == '__main__':\n"
    ++ "    raise SystemExit(main())\n"

end LeanCairo.Backend.Scarb
